from __future__ import annotations

from src.config.constants import (
    DEFAULT_EVENTS_NORMALIZED_PATH,
    DEFAULT_EVENTS_RAW_PATH,
    DEFAULT_LINEUPS_NORMALIZED_PATH,
    DEFAULT_THREE_SIXTY_NORMALIZED_PATH,
)

DEFAULT_DATA_PATH = str(DEFAULT_EVENTS_RAW_PATH)
NORMALIZED_DATA_PATH = str(DEFAULT_EVENTS_NORMALIZED_PATH)
DEFAULT_LINEUPS_PATH = str(DEFAULT_LINEUPS_NORMALIZED_PATH)
DEFAULT_FREEZE_FRAME_PATH = str(DEFAULT_THREE_SIXTY_NORMALIZED_PATH)

DATA_SCHEMA_VERSION = "2026-05-05-normalized-pipeline-v1"
MATCH_LABELS_VERSION = "2026-05-02-match-stage-v1"

MAX_PLOT_EVENTS = 600
MAX_SEQUENCE_EVENTS = 5000
